export const apiRoutes = {
  getCategories: '/categories',
  getCategory: '/categories/:slug',
  getProducts: '/products',
  getProduct: '/products/:slug',
  addReview: '/reviews/:productId',
  getCartData: '/cart',
  addToCart: '/cart/add',
  updateCartProduct: '/cart/edit',
  deleteCartProduct: '/cart',
  signIn: '/auth/sign-in',
  signUp: '/auth/sign-up',
  signOut: '/auth/sign-out',
  getMe: '/auth/profile',
  getUser: '/users/:userId',
  updateUser: '/users/:userId',
  getOrders: '/orders/user/:userId',
  getStripeConfig: '/checkout/config',
  makePayment: '/checkout/create-payment-intent'
};
