export const apiRoutes = {
  getCategories: '/categories?sort=name:asc',
  getCategory: '/categories/:slug',
  getProducts: '/products',
  getProduct: '/products/:slug',
  getReviews: '/reviews',
  getReview: '/reviews/:reviewId',
  addReview: '/reviews/:productId',
  updateReview: '/reviews/:reviewId',
  deleteReview: '/reviews',
  getCartData: '/cart',
  addToCart: '/cart/add',
  updateCartProduct: '/cart/edit',
  deleteCartProduct: '/cart',
  signIn: '/auth/sign-in',
  signUp: '/auth/sign-up',
  signOut: '/auth/sign-out',
  getMe: '/auth/profile',
  getUser: '/users/:userId',
  updateUser: '/users/:userId',
  getOrders: '/orders/user/:userId',
  getStripeConfig: '/checkout/config',
  makePayment: '/checkout/create-payment-intent',
  addNewOrder: '/checkout/add-new-order/:payment_intent_id',
};
