version: '3.8'

services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  
  server:
    build: ./server
    ports:
    - 5000:5000
    volumes:
      - ./server:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: password
      DB_NAME: ecommerce
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
     - db
     - redis
  
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: password

  redis:
      image: redis:7.2.4-alpine
      ports:
        - 6379:6379
      command: redis-server --save 20 1 --loglevel warning
      volumes:
        - redis:/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  redis:
    driver: local