import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import Footer from '@/src/components/Footer';
import ReactQueryWrapper from '../components/ReactQueryWrapper';
import ContextWrapper from '../components/ContextWrapper';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main">
          <ContextWrapper>
            <ReactQueryWrapper>
              <Navbar>{children}</Navbar>
              <Footer />
            </ReactQueryWrapper>
          </ContextWrapper>
        </div>
      </body>
    </html>
  );
}
